version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "09:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: firebase-tools
    versions:
    - 9.1.0
    - 9.2.2
  - dependency-name: ini
    versions:
    - 1.3.7
  - dependency-name: gulp-terser
    versions:
    - 2.0.0
  - dependency-name: browser-sync
    versions:
    - 2.26.13
